<%@ Page Language="VB" AutoEventWireup="true" CodeBehind="Index.aspx.vb" Inherits="MediumTrust.Index" %>

<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title>GemBox.Presentation Web Demo</title>
    <style>
        * {
            font-family: Arial;
            font-size: 10pt;
            color: rgb(45,46,45);
        }

        h1 {
            color: #0072bb;
            font-size: 30pt;
            text-align: center;
        }

        input[type="text"], textarea {
            width: 100%;
        }

        .summaries {
            font-size: 14pt;
        }

        .heading {
            font-weight: bold;
            font-size: 18pt;
            color: rgb(209,90,62);
        }

        .title {
            font-weight: bold;
            font-size: 24pt;
        }

        hr {
            display: block;
            height: 1px;
            border: 0;
            border-top: 1px solid rgb(209,90,62);
            margin: 1em 0;
            padding: 0;
        }
    </style>
</head>
<body>
    <h1>Create PowerPoint in ASP.NET</h1>
    <form id="form1" runat="server">
        <fieldset>
            <legend>Presentation form:</legend>
            <asp:TextBox ID="titleTextBox" runat="server" CssClass="title" Columns="50">ACME Corp - 4th Quarter Financial Results</asp:TextBox>
            <hr />
            <asp:TextBox ID="summaryHeadingTextBox" runat="server" CssClass="heading" Columns="30">4th Quarter Summary</asp:TextBox>
            <br />
            <br />
            <br />
            <asp:TextBox ID="summaryBulletsTextBox" runat="server" CssClass="summaries" TextMode="MultiLine" Wrap="False" Columns="70" Rows="5">3 new products/services in Research and Development.
Rollout planned for new division.
Campaigns targeting new markets.</asp:TextBox>
            <hr />
            <asp:TextBox ID="highlightsHeadingTextBox" runat="server" CssClass="heading" Columns="30">4th Quarter Financial Highlights</asp:TextBox>
            <br />
            <br />
            <br />
            <asp:GridView ID="highlightsGridView" runat="server" AutoGenerateColumns="False" BackColor="White" BorderColor="#CC9966" BorderStyle="None" BorderWidth="1px" CellPadding="4" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" Width="75%" OnRowCancelingEdit="highlightsGridView_RowCancelingEdit" OnRowDeleting="highlightsGridView_RowDeleting" OnRowEditing="highlightsGridView_RowEditing" OnRowUpdating="highlightsGridView_RowUpdating">
                <Columns>
                    <asp:BoundField DataField="Name">
                        <ItemStyle Width="25%" />
                    </asp:BoundField>
                    <asp:BoundField DataField="Estimated" HeaderText="Estimated">
                        <ItemStyle Width="25%" />
                    </asp:BoundField>
                    <asp:BoundField DataField="Change" HeaderText="% Change">
                        <ItemStyle Width="25%" />
                    </asp:BoundField>
                </Columns>
                <FooterStyle BackColor="#FFFFCC" ForeColor="#330099" />
                <HeaderStyle BackColor="#D15A3E" ForeColor="#2D2E2D" Font-Bold="False" />
                <PagerStyle BackColor="#FFFFCC" ForeColor="#330099" HorizontalAlign="Center" />
                <RowStyle BackColor="White" ForeColor="#2D2E2D" />
                <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="#663399" />
                <SortedAscendingCellStyle BackColor="#FEFCEB" />
                <SortedAscendingHeaderStyle BackColor="#AF0101" />
                <SortedDescendingCellStyle BackColor="#F6F0C0" />
                <SortedDescendingHeaderStyle BackColor="#7E0000" />
            </asp:GridView>
            <asp:LinkButton ID="addRowLinkButton" runat="server" OnClick="addRowLinkButton_Click">Add Row</asp:LinkButton>
        </fieldset>
        <br />
        <br />
        <fieldset>
            <legend>Output format:</legend>
            <asp:DropDownList ID="outputFormatDropDownList" runat="server">
                <asp:ListItem Value="pptx" Selected="True">PPTX</asp:ListItem>
                <asp:ListItem Value="pdf">PDF</asp:ListItem>
            </asp:DropDownList>
            <br /><br />
            <asp:Button ID="generateButton" runat="server" Text="Generate" OnClick="generateButton_Click" />
        </fieldset>
    </form>
</body>
</html>
